name: submon
description: "A schedule-based submission manager"
publish_to: 'none'

version: 1.0.0 # Build number will be added in CI/CD

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  slang: ^4.4.1
  slang_flutter: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
