name: submon
description: "A schedule-based submission manager"
publish_to: 'none'

version: 1.0.0 # Build number will be added in CI/CD

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  go_router: ^14.8.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  material_symbols_icons: ^4.2805.1
  animations: ^2.0.11
  flutter_hooks: ^0.21.2
  clock: ^1.1.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  drift: ^2.25.1
  drift_flutter: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.7.3
  trailing_comma_lint:
    path: ./packages/trailing_comma_lint
  go_router_builder: ^2.8.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4
  freezed: ^2.5.8
  drift_dev: ^2.25.2

flutter:
  uses-material-design: true
