name: trailing_comma_lint
description: A modified lint rule of require_trailing_commas
version: 1.0.0
repository: https://github.com/chika3742/submon/tree/main/packages/trailing_comma_lint

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^7.3.0
  analyzer_plugin: ^0.12.0
  custom_lint_builder: ^0.7.3

dev_dependencies:
  lints: ^5.0.0
